
name: data_sync_app
description: A secure data synchronization and task management application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0              # لإرسال واستقبال طلبات الـ API
  flutter_foreground_task: ^6.1.0 # لإدارة الخدمات الخلفية الدائمة
  path_provider: ^2.1.1     # لإدارة وتخزين الملفات المؤقتة
  permission_handler: ^11.1.0 # لطلب الصلاحيات من الواجهة بشكل مرن
  flutter_local_notifications: ^16.3.0 # لإظهار الإشعارات المحلية

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
